name: "ADReSS 2020 Acoustic Preprocessing Pipeline"
description: "Steps: openSMILE Feature Extraction and openXBOW Feature Extraction"
pipeline:
  - task: "extract_opensmile_features"
    unique_id: "compare_2016_lld"
    dependency: "input"
    parameters: 
      feature_set: "compare_2016"
      level: "lld"
      is_for_openxbow: True
  - task: "extract_opensmile_features"
    unique_id: "compare_2016_functionals"
    dependency: "input"
    parameters: 
      feature_set: "compare_2016"
      level: "functionals"
      is_for_openxbow: False
  - task: "extract_opensmile_features"
    unique_id: "gemaps_functionals"
    dependency: "input"
    parameters: 
      feature_set: "gemaps"
      level: "functionals" 
      is_for_openxbow: False
  - task: "extract_opensmile_features"
    unique_id: "gemaps_lld"
    dependency: "input"
    parameters: 
      feature_set: "gemaps"
      level: "lld"
      is_for_openxbow: True
  - task: "extract_opensmile_features"
    unique_id: "egemaps_functionals"
    dependency: "input"
    parameters:
      feature_set: "egemaps"
      level: "functionals"
      is_for_openxbow: False
  - task: "extract_opensmile_features"
    unique_id: "egemaps_lld"
    dependency: "input"
    parameters:
      feature_set: "egemaps"
      level: "lld" 
      is_for_openxbow: True
  - task: "extract_openxbow_features"
    unique_id: "boaw_size_500_compare_2016_lld"
    dependency: "compare_2016_lld"
    parameters: 
      openxbow_jar_app: '/Users/jimuelcelestejr/Documents/codebook/openXBOW/openXBOW.jar'
      audio_book_size: 500
      clustering: "kmeans++"
  - task: "extract_openxbow_features"
    unique_id: "boaw_size_300_compare_2016_lld"
    dependency: "compare_2016_lld"
    parameters: 
      openxbow_jar_app: '/Users/jimuelcelestejr/Documents/codebook/openXBOW/openXBOW.jar'
      audio_book_size: 300
      clustering: "kmeans++"
  - task: "extract_openxbow_features"
    unique_id: "boaw_size_100_compare_2016_lld"
    dependency: "compare_2016_lld"
    parameters: 
      openxbow_jar_app: '/Users/jimuelcelestejr/Documents/codebook/openXBOW/openXBOW.jar'
      audio_book_size: 100
      clustering: "kmeans++"